language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: QTnSkR2dCB9ZhM9s70c4TL1mAZ/laX69x6YzMrSXK6mSN7Vd1VhEm6XN8KbyxZa9bdeR4mp0+1VoZDnq0n/WyiYav/GHQWe7KVV/fT9OGH6MbIm5oxr01krojUik96tWgUFCtcYpYFXrKT024ZWV5Njc998XvngNWpSIrBvrUYs=
  - secure: UurHUs5/sX8jc4EBfdRIrC8X6q+RG55F5/AFFSOTCQL2ibV+oPtOd/1S6cb5a+5zyPcCVn1NfwgzNMMWXO6j0yhvb0QstRBiCONmiGzh3rpxWHSQPDJlc2PqB8kEstfx6PcMH8HTsYvxKgR3Q6e+9yym0u2E9pEdFuK6xP6AHec=
